import {HyppProps} from './types'

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      // HTML
      a: HyppProps<HTMLAnchorElement>
      abbr: HyppProps<HTMLElement>
      address: HyppProps<HTMLElement>
      area: HyppProps<HTMLAreaElement>
      article: HyppProps<HTMLElement>
      aside: HyppProps<HTMLElement>
      audio: HyppProps<HTMLAudioElement>
      b: HyppProps<HTMLElement>
      base: HyppProps<HTMLBaseElement>
      bdi: HyppProps<HTMLElement>
      bdo: HyppProps<HTMLElement>
      big: HyppProps<HTMLElement>
      blockquote: HyppProps<HTMLQuoteElement>
      body: HyppProps<HTMLBodyElement>
      br: HyppProps<HTMLBRElement>
      button: HyppProps<HTMLButtonElement>
      canvas: HyppProps<HTMLCanvasElement>
      caption: HyppProps<HTMLElement>
      cite: HyppProps<HTMLElement>
      code: HyppProps<HTMLElement>
      col: HyppProps<HTMLTableColElement>
      colgroup: HyppProps<HTMLTableColElement>
      data: HyppProps<HTMLDataElement>
      datalist: HyppProps<HTMLDataListElement>
      dd: HyppProps<HTMLElement>
      del: HyppProps<HTMLModElement>
      details: HyppProps<HTMLDetailsElement>
      dfn: HyppProps<HTMLElement>
      dialog: HyppProps<HTMLDialogElement>
      div: HyppProps<HTMLDivElement>
      dl: HyppProps<HTMLDListElement>
      dt: HyppProps<HTMLElement>
      em: HyppProps<HTMLElement>
      embed: HyppProps<HTMLEmbedElement>
      fieldset: HyppProps<HTMLFieldSetElement>
      figcaption: HyppProps<HTMLElement>
      figure: HyppProps<HTMLElement>
      footer: HyppProps<HTMLElement>
      form: HyppProps<HTMLFormElement>
      h1: HyppProps<HTMLHeadingElement>
      h2: HyppProps<HTMLHeadingElement>
      h3: HyppProps<HTMLHeadingElement>
      h4: HyppProps<HTMLHeadingElement>
      h5: HyppProps<HTMLHeadingElement>
      h6: HyppProps<HTMLHeadingElement>
      head: HyppProps<HTMLHeadElement>
      header: HyppProps<HTMLElement>
      hgroup: HyppProps<HTMLElement>
      hr: HyppProps<HTMLHRElement>
      html: HyppProps<HTMLHtmlElement>
      i: HyppProps<HTMLElement>
      iframe: HyppProps<HTMLIFrameElement>
      img: HyppProps<HTMLImageElement>
      input: HyppProps<HTMLInputElement>
      ins: HyppProps<HTMLModElement>
      kbd: HyppProps<HTMLElement>
      keygen: HyppProps<HTMLElement>
      label: HyppProps<HTMLLabelElement>
      legend: HyppProps<HTMLLegendElement>
      li: HyppProps<HTMLLIElement>
      link: HyppProps<HTMLLinkElement>
      main: HyppProps<HTMLElement>
      map: HyppProps<HTMLMapElement>
      mark: HyppProps<HTMLElement>
      menu: HyppProps<HTMLElement>
      menuitem: HyppProps<HTMLElement>
      meta: HyppProps<HTMLMetaElement>
      meter: HyppProps<HTMLMeterElement>
      nav: HyppProps<HTMLElement>
      noindex: HyppProps<HTMLElement>
      noscript: HyppProps<HTMLElement>
      object: HyppProps<HTMLObjectElement>
      ol: HyppProps<HTMLOListElement>
      optgroup: HyppProps<HTMLOptGroupElement>
      option: HyppProps<HTMLOptionElement>
      output: HyppProps<HTMLOutputElement>
      p: HyppProps<HTMLParagraphElement>
      param: HyppProps<HTMLParamElement>
      picture: HyppProps<HTMLPictureElement>
      pre: HyppProps<HTMLPreElement>
      progress: HyppProps<HTMLProgressElement>
      q: HyppProps<HTMLQuoteElement>
      rp: HyppProps<HTMLElement>
      rt: HyppProps<HTMLElement>
      ruby: HyppProps<HTMLElement>
      s: HyppProps<HTMLElement>
      samp: HyppProps<HTMLElement>
      slot: HyppProps<HTMLSlotElement>
      script: HyppProps<HTMLScriptElement>
      section: HyppProps<HTMLElement>
      select: HyppProps<HTMLSelectElement>
      small: HyppProps<HTMLElement>
      source: HyppProps<HTMLSourceElement>
      span: HyppProps<HTMLSpanElement>
      strong: HyppProps<HTMLElement>
      style: HyppProps<HTMLStyleElement>
      sub: HyppProps<HTMLElement>
      summary: HyppProps<HTMLElement>
      sup: HyppProps<HTMLElement>
      table: HyppProps<HTMLTableElement>
      template: HyppProps<HTMLTemplateElement>
      tbody: HyppProps<HTMLTableSectionElement>
      td: HyppProps<HTMLTableDataCellElement>
      textarea: HyppProps<HTMLTextAreaElement>
      tfoot: HyppProps<HTMLTableSectionElement>
      th: HyppProps<HTMLTableHeaderCellElement>
      thead: HyppProps<HTMLTableSectionElement>
      time: HyppProps<HTMLTimeElement>
      title: HyppProps<HTMLTitleElement>
      tr: HyppProps<HTMLTableRowElement>
      track: HyppProps<HTMLTrackElement>
      u: HyppProps<HTMLElement>
      ul: HyppProps<HTMLUListElement>
      var: HyppProps<HTMLElement>
      video: HyppProps<HTMLVideoElement>
      wbr: HyppProps<HTMLElement>
      // webview: HyppProps<HTMLWebViewElement>

      // SVG
      svg: HyppProps<SVGSVGElement>

      animate: HyppProps<SVGElement>
      animateMotion: HyppProps<SVGElement>
      animateTransform: HyppProps<SVGElement>
      circle: HyppProps<SVGCircleElement>
      clipPath: HyppProps<SVGClipPathElement>
      defs: HyppProps<SVGDefsElement>
      desc: HyppProps<SVGDescElement>
      ellipse: HyppProps<SVGEllipseElement>
      feBlend: HyppProps<SVGFEBlendElement>
      feColorMatrix: HyppProps<SVGFEColorMatrixElement>
      feComponentTransfer: HyppProps<SVGFEComponentTransferElement>
      feComposite: HyppProps<SVGFECompositeElement>
      feConvolveMatrix: HyppProps<SVGFEConvolveMatrixElement>
      feDiffuseLighting: HyppProps<SVGFEDiffuseLightingElement>
      feDisplacementMap: HyppProps<SVGFEDisplacementMapElement>
      feDistantLight: HyppProps<SVGFEDistantLightElement>
      feDropShadow: HyppProps<SVGFEDropShadowElement>
      feFlood: HyppProps<SVGFEFloodElement>
      feFuncA: HyppProps<SVGFEFuncAElement>
      feFuncB: HyppProps<SVGFEFuncBElement>
      feFuncG: HyppProps<SVGFEFuncGElement>
      feFuncR: HyppProps<SVGFEFuncRElement>
      feGaussianBlur: HyppProps<SVGFEGaussianBlurElement>
      feImage: HyppProps<SVGFEImageElement>
      feMerge: HyppProps<SVGFEMergeElement>
      feMergeNode: HyppProps<SVGFEMergeNodeElement>
      feMorphology: HyppProps<SVGFEMorphologyElement>
      feOffset: HyppProps<SVGFEOffsetElement>
      fePointLight: HyppProps<SVGFEPointLightElement>
      feSpecularLighting: HyppProps<SVGFESpecularLightingElement>
      feSpotLight: HyppProps<SVGFESpotLightElement>
      feTile: HyppProps<SVGFETileElement>
      feTurbulence: HyppProps<SVGFETurbulenceElement>
      filter: HyppProps<SVGFilterElement>
      foreignObject: HyppProps<SVGForeignObjectElement>
      g: HyppProps<SVGGElement>
      image: HyppProps<SVGImageElement>
      line: HyppProps<SVGLineElement>
      linearGradient: HyppProps<SVGLinearGradientElement>
      marker: HyppProps<SVGMarkerElement>
      mask: HyppProps<SVGMaskElement>
      metadata: HyppProps<SVGMetadataElement>
      mpath: HyppProps<SVGElement>
      path: HyppProps<SVGPathElement>
      pattern: HyppProps<SVGPatternElement>
      polygon: HyppProps<SVGPolygonElement>
      polyline: HyppProps<SVGPolylineElement>
      radialGradient: HyppProps<SVGRadialGradientElement>
      rect: HyppProps<SVGRectElement>
      stop: HyppProps<SVGStopElement>
      switch: HyppProps<SVGSwitchElement>
      symbol: HyppProps<SVGSymbolElement>
      text: HyppProps<SVGTextElement>
      textPath: HyppProps<SVGTextPathElement>
      tspan: HyppProps<SVGTSpanElement>
      use: HyppProps<SVGUseElement>
      view: HyppProps<SVGViewElement>
    }
  }
}
